[dependencies]
base = "0.9.3"
json = "https://github.com/aviate-labs/json.mo#v0.2.1"
stable = "https://github.com/aviate-labs/stable.mo#v0.1.1"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
uuid = "https://github.com/aviate-labs/uuid.mo#v0.2.1"
http-parser = "0.1.0"
certified-cache = "0.2.0"